# Site settings
name: Kunal Sonawane
title: Kunal Sonawane | Student Developer
description: A normal guy, with a knack for Computer Programming
url: https://2knal.github.io/
baseurl: ""
email: kunal.sonawane@somaiya.edu
cover: https://brittanychiang.com/img/og.png
logo: https://brittanychiang.com/img/emojis/technologist.png
# resume: https://brittanychiang.com/resume.pdf
social:
  - title: email
    url: mailto:kunal.sonawane@somaiya.edu
  - title: twitter
    url: https://twitter.com/2kunalsonawane
  # - title: medium
  #   url: https://medium.com/@thelegitlazyguy
  # - title: CodeChef
  #   url: https://www.codechef.com/users/kunal_2
  - title: github
    url: https://github.com/2knal
  - title: linkedin
    url: https://www.linkedin.com/in/kunal-sonawane-a3b397113/
# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
